.Dd February 21, 2001
.Dt DGEN 1
.Sh NAME
.Nm dgen	
.Nd Sega Genesis/MegaDrive emulator
.Sh SYNOPSIS
.Nm dgen
.Op Fl PRfhjv
.Op Fl D Ar DEMONAME
.Op Fl d Ar DEMONAME
.Op Fl n Ar USEC
.Op Fl p Ar CODE,CODE...
.Op Fl r Ar RCFILE
.Op Fl X Ar XFACT
.Op Fl Y Ar YFACT
.Op Fl S Ar FACT
.Op Fl G Ar XxY
.Op Fl s Ar SLOT
.Ar romname
.Sh DESCRIPTION
The rom image in the file
.Ar romname
is executed, as emulated on a Sega Genesis or MegaDrive running in 60Hz NTSC
mode (unless the
.Fl P
option is specified, in which case 50Hz PAL mode is used).
.Ar romname
should be in raw binary or SMD format, and may be compressed with
.Xr gzip 1 ,
.Xr zip 1 , or
.Xr bzip2 1 .
.Pp
The options are as follows:
.Bl -tag -width Fl
.It Fl P
Emulate 50Hz PAL mode (as used in European models of the MegaDrive).
.It Fl R
If running with root priviledges, set priority to -20, so no other processes
interrupt (including the X server, which can be a Bad Thing).
.It Fl f 
Run fullscreen, if possible.
.It Fl h
Show a brief synopsis of all options.
.It Fl j
Use joystick, if running on Linux with joystick drivers >= 1.0.
.It Fl v
Show the version number, and exit.
.It Fl D Ar DEMONAME
Play back a demo recorded with the
.Fl d
option.
.It Fl d Ar DEMONAME
Record a demo of the program running, which can be later replayed with the
.Fl D
switch.
.It Fl n Ar USEC
Sleep for a number of microseconds after every frame, to give time to other
processes.
.It Fl p Ar CODE,CODE...
Modify the ROM image in memory, using Game Genie or Hex style codes. Game
Genie codes are of the form
.Ar ABCD-EFGH
and Hex codes are in the form
.Ar 123456:ABCD .
To specify more than one code, separate them with commas (do
.Ar not
use spaces).
.It Fl r Ar RCFILE
Parse another rc file after $HOME/.dgen/dgenrc. Values in the specified file
override those in the preceding files.
.It Fl X Ar XFACT
Scale the window XFACT times in the X direction. XFACT must be a positive
integer.
.It Fl Y Ar YFACT
Scale the window YFACT times in the Y direction. YFACT must be a positive
integer.
.It Fl S Ar FACT
Scale the window FACT times in both directions. FACT must be a positive integer.
.It Fl G Ar XxY
Use OpenGL to render the screen, if available. The parameter is the width
and height of the desired screen (e.g. 640x480, 800x600, etc.)
.It Fl s Ar SLOT
Load the saved state from the given slot at startup (0-9)
.El
.Sh FILES
.Bl -tag -width $HOME/.dgen/dgen/saves/* -compact
.It Pa $HOME/.dgen/dgenrc
Contains user settings for the emulator.
.It Pa $HOME/.dgen/saves/*
Save states generated by the emulator.
.It Pa $HOME/.dgen/ram/*
Battery-backup RAM images, generated by the emulator for ROMs with save RAM.
.El
.Sh SEE ALSO
.Xr gzip 1 ,
.Xr bzip2 1 ,
.Xr zip 1 ,
.Xr dgenrc 5
.Sh AUTHORS
This
manual page was written by
.An Joe Groff Aq joe@pknet.com .
.Sh BUGS
PAL mode does not work very well yet. Numerous buffer overruns
(think twice before making dgen setuid-root).
.Pp
Send any bugs you find (and fixes too, please :) to
.An Joe Groff Aq joe@pknet.com .
